#!/bin/bash
# 16-if_only: Change owner of 'hello' to vincent only if owned by guillaume

file="hello"
current_owner=$(ls -ld "$file" | awk '{print $3}')

if [ "$current_owner" = "guillaume" ]; then
    chown vincent "$file"
fi
